// SPDX-License-Identifier: GPL-3.0-or-later
// NX-Nexus -- read/delete view of installed titles.
//
// Each installed content meta (a base game, a patch, a DLC) becomes one folder:
//
//   Game Name [0100000000010000] v0 Application/
//       Game Name [0100000000010000] v0.nsp    <- synthesised on read
//       icon.jpg
//       info.txt
//
// The .nsp does not exist anywhere: its PFS0 header is generated by
// nsp_builder, and its body is the registered NCAs read straight out of ncm.
// Dragging it to a PC therefore extracts the title without ever staging a copy
// on the SD card.
//
// Deleting a title folder deletes the title. That is destructive and
// irreversible, so it happens only on an explicit DeleteObject from the host --
// which is the user dragging the folder to the trash in their own file manager.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "nexus/storage.h"
#include "nexus/mtp_types.h"
#include "nexus/nsp_builder.h"
#include "nexus/es.h"
#include "nexus/sysinfo.h"
#include "nexus/format.h"
#include "nexus/log.h"

#define TITLES_MAX       512
#define TITLE_NAME_LEN   192
#define TITLE_BASE_LEN   (TITLE_NAME_LEN - 8)
#define TITLE_DISPLAY_MAX 96

#define NSP_HEADER_CAP   8192
#define TIK_CAP          0x1000
#define CERT_CAP         0x2000

// What one synthesised NSP entry reads from.
typedef enum {
    NspSrc_Nca = 0,
    NspSrc_Ticket,
    NspSrc_Cert,
} NspSrcKind;

typedef struct {
    char              name[TITLE_NAME_LEN];
    NcmContentMetaKey key;
    u8                storage_id;   // NcmStorageId
} TitleEntry;

typedef struct {
    char description[64];

    TitleEntry entries[TITLES_MAX];
    u32        count;
    bool       listed;

    // Everything below describes the one title currently open. Building an NSP
    // layout costs several ncm round trips, so it is done once and reused for
    // the whole of a transfer.
    int  open_index;
    bool open_valid;

    NspBuilder   nsp;
    u8           nsp_header[NSP_HEADER_CAP];
    NcmContentId nsp_ids[NSP_MAX_ENTRIES];
    u8           nsp_src[NSP_MAX_ENTRIES];   // NspSrcKind
    char         nsp_filename[TITLE_NAME_LEN];

    u8     tik[TIK_CAP];
    size_t tik_len;
    u8     cert[CERT_CAP];
    size_t cert_len;

    NcmContentStorage cs;
    bool              cs_open;
    u8                cs_storage;

    // Icon and info, generated for the open title.
    u8    *icon;
    size_t icon_len;
    char   info[512];
} TitlesStorage;

// ---------------------------------------------------------------------------
// Listing
// ---------------------------------------------------------------------------

static bool lookup_display_name(u64 application_id, char *out, size_t out_size)
{
    NsApplicationControlData *data =
        (NsApplicationControlData *)malloc(sizeof(NsApplicationControlData));
    if (data == NULL) return false;

    bool ok = false;
    u64 actual = 0;

    if (R_SUCCEEDED(nsGetApplicationControlData(NsApplicationControlSource_Storage,
                                                application_id, data,
                                                sizeof(*data), &actual))
        && actual >= sizeof(data->nacp)) {
        NacpLanguageEntry *entry = NULL;
        if (R_SUCCEEDED(nacpGetLanguageEntry(&data->nacp, &entry))
            && entry != NULL && entry->name[0] != '\0') {
            nexusSanitiseUtf8(entry->name, out, out_size);
            ok = (out[0] != '\0');
        }
    }

    free(data);
    return ok;
}

// Patches and add-on content carry derived ids; their artwork and name live
// with the base application.
static u64 base_application_id(u64 id, u8 meta_type)
{
    switch (meta_type) {
        case NcmContentMetaType_Patch:        return id ^ 0x800ull;
        case NcmContentMetaType_AddOnContent: return (id ^ 0x1000ull) & ~0xFFFull;
        default:                              return id;
    }
}

static const char *meta_type_name(u8 t)
{
    switch (t) {
        case NcmContentMetaType_Application:   return "Application";
        case NcmContentMetaType_Patch:         return "Update";
        case NcmContentMetaType_AddOnContent:  return "DLC";
        case NcmContentMetaType_SystemProgram: return "SystemProgram";
        case NcmContentMetaType_SystemData:    return "SystemData";
        case NcmContentMetaType_Delta:         return "Delta";
        case NcmContentMetaType_DataPatch:     return "DataPatch";
        default:                               return "Other";
    }
}

static void build_title_name(TitlesStorage *s, const NcmContentMetaKey *key,
                             char *out, size_t out_size)
{
    char display[TITLE_DISPLAY_MAX];
    if (!lookup_display_name(base_application_id(key->id, key->type),
                             display, sizeof(display))) {
        snprintf(display, sizeof(display), "Unknown");
    }

    char base[TITLE_BASE_LEN];
    snprintf(base, sizeof(base), "%s [%016llx] v%u %s",
             display, (unsigned long long)key->id, key->version,
             meta_type_name(key->type));

    snprintf(out, out_size, "%s", base);

    for (u32 n = 2; n < 100; n++) {
        bool clash = false;
        for (u32 i = 0; i < s->count; i++) {
            if (strcmp(s->entries[i].name, out) == 0) { clash = true; break; }
        }
        if (!clash) return;
        snprintf(out, out_size, "%s (%u)", base, n);
    }
}

// Enumerates every content meta on one storage.
//
// ncmContentMetaDatabaseList has no offset parameter: it always returns from
// the beginning and reports how many exist in total. Calling it in a loop
// therefore returns the same entries over and over -- which is exactly how an
// earlier version of this produced a listing full of duplicates. The buffer
// has to be big enough to take everything in one call.
static void list_storage(TitlesStorage *s, NcmStorageId storage_id)
{
    NcmContentMetaDatabase db;
    if (R_FAILED(ncmOpenContentMetaDatabase(&db, storage_id))) return;

    const s32 room = (s32)(TITLES_MAX - s->count);
    if (room <= 0) { ncmContentMetaDatabaseClose(&db); return; }

    NcmContentMetaKey *keys = (NcmContentMetaKey *)calloc((size_t)room, sizeof(*keys));
    if (keys == NULL) { ncmContentMetaDatabaseClose(&db); return; }

    s32 total = 0, written = 0;
    const Result rc = ncmContentMetaDatabaseList(&db, &total, &written, keys, room,
                                                 NcmContentMetaType_Unknown,
                                                 0, 0, UINT64_MAX,
                                                 NcmContentInstallType_Full);
    ncmContentMetaDatabaseClose(&db);

    if (R_SUCCEEDED(rc) && written > 0) {
        for (s32 i = 0; i < written && s->count < TITLES_MAX; i++) {
            TitleEntry *e = &s->entries[s->count];
            e->key        = keys[i];
            e->storage_id = (u8)storage_id;
            build_title_name(s, &keys[i], e->name, sizeof(e->name));
            s->count++;
        }

        if (total > written) {
            LOG_W("titles: storage %u holds %d entries, listed %d",
                  storage_id, total, written);
        }
    }

    free(keys);
}

static Result titles_list(TitlesStorage *s)
{
    if (s->listed) return 0;

    s->count = 0;
    list_storage(s, NcmStorageId_SdCard);
    list_storage(s, NcmStorageId_BuiltInUser);

    s->listed = true;
    LOG_I("titles: %u installed content meta entries found on %s",
          s->count, nexusSysInfoStorageName());
    return 0;
}

static int titles_find(TitlesStorage *s, const char *name)
{
    for (u32 i = 0; i < s->count; i++) {
        if (strcmp(s->entries[i].name, name) == 0) return (int)i;
    }
    return -1;
}

// ---------------------------------------------------------------------------
// Opening one title: build its NSP layout, icon and info
// ---------------------------------------------------------------------------

static void titles_close_open(TitlesStorage *s)
{
    if (s->cs_open) {
        ncmContentStorageClose(&s->cs);
        s->cs_open = false;
    }
    free(s->icon);
    s->icon      = NULL;
    s->icon_len  = 0;
    s->open_index = -1;
    s->open_valid = false;
    s->tik_len    = 0;
    s->cert_len   = 0;
}

// Fetches the ticket and certificate for a rights id, if the title has one.
static void load_ticket(TitlesStorage *s, const NcmRightsId *rights_id)
{
    s->tik_len  = 0;
    s->cert_len = 0;

    u64 tik_size = 0, cert_size = 0;
    if (R_FAILED(nexusEsGetCommonTicketAndCertificateSize(rights_id->rights_id.c,
                                                          sizeof(rights_id->rights_id.c),
                                                          &tik_size, &cert_size))) {
        LOG_D("titles: no common ticket for this title");
        return;
    }
    if (tik_size == 0 || tik_size > TIK_CAP || cert_size == 0 || cert_size > CERT_CAP) {
        LOG_W("titles: ticket (%llu) or cert (%llu) too large to embed",
              (unsigned long long)tik_size, (unsigned long long)cert_size);
        return;
    }

    u64 got_tik = 0, got_cert = 0;
    if (R_FAILED(nexusEsGetCommonTicketAndCertificateData(rights_id->rights_id.c,
                                                          sizeof(rights_id->rights_id.c),
                                                          s->tik, TIK_CAP,
                                                          s->cert, CERT_CAP,
                                                          &got_tik, &got_cert))) {
        LOG_W("titles: reading the common ticket failed");
        return;
    }

    s->tik_len  = (size_t)got_tik;
    s->cert_len = (size_t)got_cert;
}

// Formats a content id as the 32 hex characters used in an NCA filename.
static void content_id_hex(const NcmContentId *id, char *out, size_t out_size)
{
    static const char hex[] = "0123456789abcdef";
    if (out_size < 33) { if (out_size) out[0] = '\0'; return; }

    for (size_t i = 0; i < 0x10; i++) {
        out[i * 2]       = hex[(id->c[i] >> 4) & 0xF];
        out[(i * 2) + 1] = hex[id->c[i] & 0xF];
    }
    out[32] = '\0';
}

static bool titles_open(TitlesStorage *s, u32 index)
{
    if (index >= s->count) return false;
    if (s->open_valid && s->open_index == (int)index) return true;

    titles_close_open(s);

    TitleEntry *e = &s->entries[index];

    if (R_FAILED(ncmOpenContentStorage(&s->cs, (NcmStorageId)e->storage_id))) {
        LOG_W("titles: OpenContentStorage(%u) failed", e->storage_id);
        return false;
    }
    s->cs_open    = true;
    s->cs_storage = e->storage_id;

    NcmContentMetaDatabase db;
    if (R_FAILED(ncmOpenContentMetaDatabase(&db, (NcmStorageId)e->storage_id))) {
        titles_close_open(s);
        return false;
    }

    NcmContentInfo infos[NSP_MAX_ENTRIES];
    s32 written = 0;
    const Result rc = ncmContentMetaDatabaseListContentInfo(&db, &written, infos,
                                                            NSP_MAX_ENTRIES, &e->key, 0);
    ncmContentMetaDatabaseClose(&db);

    if (R_FAILED(rc) || written <= 0) {
        LOG_W("titles: ListContentInfo failed for %s", e->name);
        titles_close_open(s);
        return false;
    }

    // Any content of this title that needs a title key shares one rights id;
    // fetching it from the first content that has one is enough.
    for (s32 i = 0; i < written; i++) {
        NcmRightsId rights_id;
        memset(&rights_id, 0, sizeof(rights_id));
        if (R_FAILED(ncmContentStorageGetRightsIdFromContentId(&s->cs, &rights_id,
                                                               &infos[i].content_id,
                                                               FsContentAttributes_All))) {
            continue;
        }

        // An all-zero rights id means the content is not title-key encrypted.
        bool empty = true;
        for (size_t b = 0; b < sizeof(rights_id.rights_id.c); b++) {
            if (rights_id.rights_id.c[b] != 0) { empty = false; break; }
        }
        if (empty) continue;

        load_ticket(s, &rights_id);
        break;
    }

    // Build the NSP layout.
    nspBuilderInit(&s->nsp, s->nsp_header, sizeof(s->nsp_header));
    u32 slot = 0;

    for (s32 i = 0; i < written && slot < NSP_MAX_ENTRIES; i++) {
        char hex[33];
        content_id_hex(&infos[i].content_id, hex, sizeof(hex));

        char name[NSP_MAX_NAME_LEN];
        if (infos[i].content_type == NcmContentType_Meta) {
            snprintf(name, sizeof(name), "%s.cnmt.nca", hex);
        } else {
            snprintf(name, sizeof(name), "%s.nca", hex);
        }

        u64 size = 0;
        ncmContentInfoSizeToU64(&infos[i], &size);

        if (nspBuilderAdd(&s->nsp, name, size) != NexusFmt_Ok) break;

        s->nsp_ids[slot] = infos[i].content_id;
        s->nsp_src[slot] = NspSrc_Nca;
        slot++;
    }

    if (s->tik_len > 0 && s->cert_len > 0 && slot + 2 <= NSP_MAX_ENTRIES) {
        // Ticket and certificate are named after the rights id by convention,
        // but any name works -- the installer matches on the extension.
        char hex[33];
        content_id_hex(&s->nsp_ids[0], hex, sizeof(hex));

        char tname[NSP_MAX_NAME_LEN], cname[NSP_MAX_NAME_LEN];
        snprintf(tname, sizeof(tname), "%016llx.tik", (unsigned long long)e->key.id);
        snprintf(cname, sizeof(cname), "%016llx.cert", (unsigned long long)e->key.id);

        if (nspBuilderAdd(&s->nsp, tname, s->tik_len) == NexusFmt_Ok) {
            s->nsp_src[slot++] = NspSrc_Ticket;
        }
        if (nspBuilderAdd(&s->nsp, cname, s->cert_len) == NexusFmt_Ok) {
            s->nsp_src[slot++] = NspSrc_Cert;
        }
    }

    if (nspBuilderFinalize(&s->nsp) != NexusFmt_Ok) {
        LOG_W("titles: could not build an NSP layout for %s", e->name);
        titles_close_open(s);
        return false;
    }

    snprintf(s->nsp_filename, sizeof(s->nsp_filename), "%s.nsp", e->name);

    // Icon and info, both cheap enough to build eagerly once the title is open.
    NsApplicationControlData *data =
        (NsApplicationControlData *)malloc(sizeof(NsApplicationControlData));
    if (data != NULL) {
        u64 actual = 0;
        if (R_SUCCEEDED(nsGetApplicationControlData(NsApplicationControlSource_Storage,
                                                    base_application_id(e->key.id, e->key.type),
                                                    data, sizeof(*data), &actual))
            && actual > sizeof(data->nacp)) {

            s->icon_len = (size_t)(actual - sizeof(data->nacp));
            s->icon = (u8 *)malloc(s->icon_len);
            if (s->icon != NULL) {
                memcpy(s->icon, data->icon, s->icon_len);
            } else {
                s->icon_len = 0;
            }
        }
        free(data);
    }

    snprintf(s->info, sizeof(s->info),
             "Title ID   : %016llx\n"
             "Version    : %u\n"
             "Type       : %s\n"
             "Storage    : %s\n"
             "Contents   : %d\n"
             "NSP size   : %llu bytes\n"
             "Ticket     : %s\n"
             "Booted from: %s\n",
             (unsigned long long)e->key.id, e->key.version,
             meta_type_name(e->key.type),
             e->storage_id == NcmStorageId_SdCard ? "SD card" : "internal",
             written,
             (unsigned long long)nspBuilderTotalSize(&s->nsp),
             s->tik_len > 0 ? "yes" : "none",
             nexusSysInfoStorageName());

    s->open_index = (int)index;
    s->open_valid = true;
    return true;
}

// ---------------------------------------------------------------------------
// Storage ops
// ---------------------------------------------------------------------------

static const char *titles_description(NexusStorage *self)
{
    return ((TitlesStorage *)self->impl)->description;
}

static Result titles_get_info(NexusStorage *self, NexusStorageInfo *out)
{
    (void)self;
    memset(out, 0, sizeof(*out));
    out->storage_type      = MtpStorageType_FixedROM;
    out->filesystem_type   = MtpFsType_GenericHierarchical;
    // Read plus delete: MTP has an access code for exactly this.
    out->access_capability = MtpAccess_ReadOnlyWithObjectDelete;
    out->free_objects      = 0xFFFFFFFFu;

    // Titles span both content storages; reporting their combined size keeps
    // the host from drawing this as a full, red volume.
    const NcmStorageId ids[] = { NcmStorageId_SdCard, NcmStorageId_BuiltInUser };
    for (size_t i = 0; i < sizeof(ids) / sizeof(ids[0]); i++) {
        NcmContentStorage cs;
        if (R_FAILED(ncmOpenContentStorage(&cs, ids[i]))) continue;

        s64 total = 0, freesp = 0;
        if (R_SUCCEEDED(ncmContentStorageGetTotalSpaceSize(&cs, &total))) {
            out->capacity_bytes += (u64)total;
        }
        if (R_SUCCEEDED(ncmContentStorageGetFreeSpaceSize(&cs, &freesp))) {
            out->free_bytes += (u64)freesp;
        }
        ncmContentStorageClose(&cs);
    }
    return 0;
}

// Splits "/Title Folder/file" into its two components.
static bool split(const char *path, char *head, size_t head_size,
                  char *tail, size_t tail_size)
{
    if (path == NULL || path[0] != '/') return false;

    const char *start = path + 1;
    const char *slash = strchr(start, '/');
    const size_t head_len = (slash != NULL) ? (size_t)(slash - start) : strlen(start);
    if (head_len >= head_size) return false;

    memcpy(head, start, head_len);
    head[head_len] = '\0';

    snprintf(tail, tail_size, "%s", (slash != NULL && slash[1] != '\0') ? slash + 1 : "");
    return true;
}

static Result titles_enumerate(NexusStorage *self, const char *dir_path,
                               NexusEnumCallback cb, void *user)
{
    TitlesStorage *s = (TitlesStorage *)self->impl;
    titles_list(s);

    if (strcmp(dir_path, "/") == 0) {
        for (u32 i = 0; i < s->count; i++) {
            if (!cb(user, s->entries[i].name, true, 0)) break;
        }
        return 0;
    }

    char head[TITLE_NAME_LEN], tail[TITLE_NAME_LEN];
    if (!split(dir_path, head, sizeof(head), tail, sizeof(tail))) {
        return MAKERESULT(Module_Libnx, LibnxError_BadInput);
    }
    if (tail[0] != '\0') return MAKERESULT(Module_Libnx, LibnxError_NotFound);

    const int index = titles_find(s, head);
    if (index < 0 || !titles_open(s, (u32)index)) {
        return MAKERESULT(Module_Libnx, LibnxError_NotFound);
    }

    if (!cb(user, s->nsp_filename, false, (s64)nspBuilderTotalSize(&s->nsp))) return 0;
    if (s->icon_len > 0 && !cb(user, "icon.jpg", false, (s64)s->icon_len)) return 0;
    cb(user, "info.txt", false, (s64)strlen(s->info));
    return 0;
}

static Result titles_stat(NexusStorage *self, const char *path, bool *out_is_dir, s64 *out_size)
{
    TitlesStorage *s = (TitlesStorage *)self->impl;

    if (strcmp(path, "/") == 0) {
        if (out_is_dir) *out_is_dir = true;
        if (out_size)   *out_size   = 0;
        return 0;
    }

    titles_list(s);

    char head[TITLE_NAME_LEN], tail[TITLE_NAME_LEN];
    if (!split(path, head, sizeof(head), tail, sizeof(tail))) {
        return MAKERESULT(Module_Libnx, LibnxError_BadInput);
    }

    const int index = titles_find(s, head);
    if (index < 0) return MAKERESULT(Module_Libnx, LibnxError_NotFound);

    if (tail[0] == '\0') {
        if (out_is_dir) *out_is_dir = true;
        if (out_size)   *out_size   = 0;
        return 0;
    }

    if (!titles_open(s, (u32)index)) return MAKERESULT(Module_Libnx, LibnxError_NotFound);

    if (out_is_dir) *out_is_dir = false;

    if (strcmp(tail, s->nsp_filename) == 0) {
        if (out_size) *out_size = (s64)nspBuilderTotalSize(&s->nsp);
        return 0;
    }
    if (strcmp(tail, "icon.jpg") == 0 && s->icon_len > 0) {
        if (out_size) *out_size = (s64)s->icon_len;
        return 0;
    }
    if (strcmp(tail, "info.txt") == 0) {
        if (out_size) *out_size = (s64)strlen(s->info);
        return 0;
    }

    return MAKERESULT(Module_Libnx, LibnxError_NotFound);
}

// Serves a byte range of the synthesised NSP.
static Result read_virtual_nsp(TitlesStorage *s, u64 offset, void *buffer,
                               size_t size, size_t *out_read)
{
    u8 *dst = (u8 *)buffer;
    size_t done = 0;

    while (done < size) {
        NspLocation loc;
        if (nspBuilderLocate(&s->nsp, offset + done, &loc) != NexusFmt_Ok) break;

        // Never read across a region boundary in one go.
        size_t chunk = size - done;
        if ((u64)chunk > loc.run) chunk = (size_t)loc.run;

        if (loc.in_header) {
            size_t header_size = 0;
            const u8 *header = nspBuilderHeader(&s->nsp, &header_size);
            memcpy(dst + done, header + loc.header_off, chunk);
        } else {
            const u8 kind = s->nsp_src[loc.entry_index];

            if (kind == NspSrc_Ticket) {
                if (loc.entry_off + chunk > s->tik_len) break;
                memcpy(dst + done, s->tik + loc.entry_off, chunk);
            } else if (kind == NspSrc_Cert) {
                if (loc.entry_off + chunk > s->cert_len) break;
                memcpy(dst + done, s->cert + loc.entry_off, chunk);
            } else {
                // Straight out of ncm content storage -- no staging anywhere.
                if (R_FAILED(ncmContentStorageReadContentIdFile(
                        &s->cs, dst + done, chunk,
                        &s->nsp_ids[loc.entry_index], (s64)loc.entry_off))) {
                    break;
                }
            }
        }

        done += chunk;
    }

    if (out_read) *out_read = done;
    return (done > 0 || size == 0) ? 0 : MAKERESULT(Module_Libnx, LibnxError_IoError);
}

static Result titles_read(NexusStorage *self, const char *path, u64 offset,
                          void *buffer, size_t size, size_t *out_read)
{
    TitlesStorage *s = (TitlesStorage *)self->impl;
    if (out_read) *out_read = 0;

    titles_list(s);

    char head[TITLE_NAME_LEN], tail[TITLE_NAME_LEN];
    if (!split(path, head, sizeof(head), tail, sizeof(tail))) {
        return MAKERESULT(Module_Libnx, LibnxError_BadInput);
    }

    const int index = titles_find(s, head);
    if (index < 0 || !titles_open(s, (u32)index)) {
        return MAKERESULT(Module_Libnx, LibnxError_NotFound);
    }

    if (strcmp(tail, s->nsp_filename) == 0) {
        return read_virtual_nsp(s, offset, buffer, size, out_read);
    }

    // Icon and info are small and already in memory.
    const u8 *src = NULL;
    size_t    len = 0;

    if (strcmp(tail, "icon.jpg") == 0) { src = s->icon;            len = s->icon_len; }
    else if (strcmp(tail, "info.txt") == 0) { src = (const u8 *)s->info; len = strlen(s->info); }
    else return MAKERESULT(Module_Libnx, LibnxError_NotFound);

    if (src == NULL || offset >= len) return 0;

    size_t chunk = len - (size_t)offset;
    if (chunk > size) chunk = size;
    memcpy(buffer, src + offset, chunk);
    if (out_read) *out_read = chunk;
    return 0;
}

static Result titles_remove(NexusStorage *self, const char *path, bool is_dir)
{
    TitlesStorage *s = (TitlesStorage *)self->impl;

    // Only a whole title folder can be deleted; the files inside it are
    // synthetic and deleting one individually is meaningless.
    if (!is_dir) return MAKERESULT(Module_Libnx, LibnxError_BadInput);

    titles_list(s);

    char head[TITLE_NAME_LEN], tail[TITLE_NAME_LEN];
    if (!split(path, head, sizeof(head), tail, sizeof(tail))) {
        return MAKERESULT(Module_Libnx, LibnxError_BadInput);
    }
    if (tail[0] != '\0') return MAKERESULT(Module_Libnx, LibnxError_BadInput);

    const int index = titles_find(s, head);
    if (index < 0) return MAKERESULT(Module_Libnx, LibnxError_NotFound);

    TitleEntry *e = &s->entries[index];

    // Deleting an Application removes its updates and DLC too, which is what
    // ns does and what a user dragging a game to the trash expects.
    //
    // Updates and DLC are a different matter: removing just one means editing
    // the application's record rather than deleting the application, and
    // getting that wrong leaves the base game unlaunchable. Until that path is
    // implemented and tested, refuse rather than risk it.
    if (e->key.type != NcmContentMetaType_Application) {
        LOG_W("titles: refusing to delete %s -- only base applications can be "
              "deleted for now", e->name);
        return MAKERESULT(Module_Libnx, LibnxError_BadInput);
    }

    if (s->open_valid && s->open_index == index) titles_close_open(s);

    LOG_W("titles: deleting %s (%016llx)", e->name, (unsigned long long)e->key.id);

    const Result rc = nsDeleteApplicationCompletely(e->key.id);
    if (R_FAILED(rc)) {
        LOG_E("titles: DeleteApplicationCompletely failed (0x%x)", rc);
        return rc;
    }

    // The cached listing is now wrong.
    s->listed = false;
    LOG_I("titles: deleted %s", e->name);
    return 0;
}

static const NexusStorageOps g_titles_ops = {
    .description = titles_description,
    .get_info    = titles_get_info,
    .enumerate   = titles_enumerate,
    .stat        = titles_stat,
    .read        = titles_read,
    .write_begin = NULL,
    .write_chunk = NULL,
    .write_end   = NULL,
    .mkdir       = NULL,
    .remove      = titles_remove,
    .move        = NULL,
    .copy        = NULL,
};

Result nexusStorageTitlesCreate(NexusStorage *out, u32 storage_id, const char *description)
{
    TitlesStorage *s = (TitlesStorage *)calloc(1, sizeof(TitlesStorage));
    if (s == NULL) return MAKERESULT(Module_Libnx, LibnxError_OutOfMemory);

    s->open_index = -1;
    snprintf(s->description, sizeof(s->description), "%s", description);

    out->storage_id = storage_id;
    out->ops        = &g_titles_ops;
    out->impl       = s;
    out->present    = true;

    LOG_I("storage: %s registered", description);
    return 0;
}

void nexusStorageTitlesInvalidate(NexusStorage *self)
{
    TitlesStorage *s = (TitlesStorage *)self->impl;
    titles_close_open(s);
    s->listed = false;
    s->count  = 0;
}
